import { Header } from "@/components/Header";
import { Buildings } from "@phosphor-icons/react/dist/ssr/Buildings";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Open_Sans, Poppins } from "next/font/google";
import SessionProvider from "../context/session-provider";
import "./globals.css";

const openSans = Open_Sans({ subsets: ["latin"] });
export const poppins = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${openSans.className}`}>
        <SessionProvider>
          <Header />
          {children}
        </SessionProvider>
        <footer className="flex h-24 text-white bg-sky-600 items-center px-4 md:px-12">
          <section className="flex flex-col flex-1 capitalize">
            <span>
              © {new Date().getFullYear()} real state site. all rights reserved.
            </span>
          </section>
          <section className="flex justify-end">
            <Buildings size={40} color="white" weight="bold" />
          </section>
        </footer>
      </body>
    </html>
  );
}
