import { properties } from "@/app/test/page";
import { Metadata } from "next";
import { notFound } from "next/navigation";
import { v4 as uuidv4 } from "uuid";

export const revalidate = 60;

interface PageProps {
  params: { slug: string[] };
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PropertyPage({ params: { slug } }: PageProps) {
  const slugPropertyID = slug[2].split("_id_")[1];

  const property = properties.find(
    (property) => property.id === slugPropertyID
  );

  if (!property) {
    notFound();
  }

  return (
    <>
      <h1>{property.description}</h1>
      <footer>{uuidv4()}</footer>
    </>
  );
}

export async function generateStaticParams() {
  console.log("gerando os params");

  return properties.map((property) => ({
    slug: [property.address.city, property.address.state],
  }));
}
